Workflow update

diff --git a/.github/workflows/lint-test.yaml b/.github/workflows/lint-test.yaml
--- a/.github/workflows/lint-test.yaml
+++ b/.github/workflows/lint-test.yaml
@@ -1,39 +1,36 @@
 name: Lint and Test Charts
 
-on: pull_request
+# Controls when the action will run.
+on:
+  # Triggers the workflow on push or pull request events but only for the master branch
+  push:
+    branches: ['master', '*']
+  pull_request:
+    branches: ['master', '*']
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+env:
+  GITHUB_TOKEN: '${{ secrets.SECRET_GITHUB_TOKEN }}'
 
 jobs:
   lint-test:
     runs-on: ubuntu-latest
-    # strategy:
-    #   matrix:
-    #     # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
-    #     python-version: [3.5, 3.6, 3.7.4, 3.8, 3.9]
+
     steps:
       - name: Checkout
         uses: actions/checkout@v2
 
-        # with:
-        #   fetch-depth: 0
       - name: Fetch history
         run: |
-          apt-get update;
-          apt-get -y --no-install-recommends --no-install-suggests install git build-essential bash curl wget zip tar gzip;
-          git fetch --prune --unshallow || git fetch --prune
+          git fetch --prune --unshallow || echo "Unable to do git fetch --prune --unshallow ..."
+          git fetch --prune || echo "Unable to do git fetch --prune ..."
 
       - name: Configure Git
         run: |
-          git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
-
-      # - name: Install ACT deps
-      #   if: ${{ !env.ACT }}
-      #   run: |
-      #     /bin/sh -c "ls"
-
-      # - name: Set up Helm
-      #   uses: azure/setup-helm@v1
-      #   id: install
+          git config user.name "$GITHUB_ACTOR" || echo "Unable to set git config user.name ..."
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" || echo "Unable to set git config user.email ..."
 
       # See https://github.com/helm/chart-releaser-action/issues/6
       - name: Install Helm
@@ -42,11 +39,23 @@ jobs:
           chmod 700 get_helm.sh
           ./get_helm.sh
 
-      - uses: actions/setup-python@v2
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v2
         with:
+          python-version: 3.8
           token: '${{ secrets.SECRET_GITHUB_TOKEN }}'
-          python-version: '3.8.6' # ${{ matrix.python-version }}
-          # architecture: 'x64'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8 pytest
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+      # - uses: actions/setup-python@v2
+      #   with:
+      #     token: '${{ secrets.SECRET_GITHUB_TOKEN }}'
+      #     python-version: '3.8' # ${{ matrix.python-version }}
+      #     # architecture: 'x64'
 
       - name: Set up chart-testing
         uses: helm/chart-testing-action@v2.0.1
